# Generated by Django 5.0.7 on 2024-07-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchandotherbuilding',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchandotherbuilding',
            name='architecture_and_design',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchandotherbuilding',
            name='community_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchandotherbuilding',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchandotherbuilding',
            name='functions_and_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchandotherbuilding',
            name='governance_and_leadership',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchandotherbuilding',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchandotherbuilding',
            name='notable_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchcommunity',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchcommunity',
            name='beliefs_and_teachings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchcommunity',
            name='community_life',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchcommunity',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchcommunity',
            name='governance_and_structure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchcommunity',
            name='historical_figures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchcommunity',
            name='worship_practices_and_rituals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionbuilding',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionbuilding',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionbuilding',
            name='governance_and_leadership',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionbuilding',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionbuilding',
            name='impact_and_reach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionbuilding',
            name='mission_and_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionbuilding',
            name='notable_achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionbuilding',
            name='services_and_programs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='majorcelebrationhistoricalevent',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='majorcelebrationhistoricalevent',
            name='commemoration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='majorcelebrationhistoricalevent',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='majorcelebrationhistoricalevent',
            name='impact_and_significance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='majorcelebrationhistoricalevent',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='majorcelebrationhistoricalevent',
            name='the_event',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='early_life',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='influence_and_legacy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='key_achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='personal_reflections',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='veneration_recognition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
