# Generated by Django 5.0.7 on 2024-08-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('iceapp', '0004_rename_introduction_majorcelebrationhistoricalevent_about_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchandotherbuilding',
            name='events',
        ),
        migrations.RemoveField(
            model_name='churchandotherbuilding',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='churchandotherbuilding',
            name='people',
        ),
        migrations.RemoveField(
            model_name='institutionbuilding',
            name='church_buildings',
        ),
        migrations.RemoveField(
            model_name='institutionbuilding',
            name='events',
        ),
        migrations.RemoveField(
            model_name='institutionbuilding',
            name='people',
        ),
        migrations.RemoveField(
            model_name='majorcelebrationhistoricalevent',
            name='church_buildings',
        ),
        migrations.RemoveField(
            model_name='majorcelebrationhistoricalevent',
            name='institutions',
        ),
        migrations.RemoveField(
            model_name='majorcelebrationhistoricalevent',
            name='people',
        ),
        migrations.RemoveField(
            model_name='person',
            name='church_buildings',
        ),
        migrations.RemoveField(
            model_name='person',
            name='events',
        ),
        migrations.RemoveField(
            model_name='person',
            name='institutionss',
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='church_and_other_building_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='church_and_other_building_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='church_community_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='church_community_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='institution_building_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='institution_building_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='major_celebration_historical_event_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='major_celebration_historical_event_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='person_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='person_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
