# Generated by Django 5.0.7 on 2024-08-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0006_churchandotherbuilding_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchandotherbuilding',
            name='category',
            field=models.CharField(choices=[('Diocese', 'Diocese'), ('Basilica', 'Basilica'), ('Cathedrals', 'Cathedrals'), ('Parishes', 'Parishes'), ('Pilgrime Centers', 'Pilgrime Centers'), ('Congregations', 'Congregations'), ('Pios Associations', 'Pios Associations')], default='Diocese', max_length=60),
            preserve_default=False,
        ),
    ]
