# Generated by Django 5.0.7 on 2024-08-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0008_institutionbuilding_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchcommunity',
            name='category',
            field=models.CharField(choices=[('Communities', 'Communities'), ('Diocese', 'Diocese'), ('Congregations', 'Congregations'), ('Pios Associations', 'Pios Associations')], default='Communities', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='category',
            field=models.CharField(choices=[('Historical Events', 'Historical Events'), ('Major Celebrations', 'Major Celebrations')], default='Historical Events', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('Clergy', 'Clergy'), ('Laity', 'Laity'), ('Saints', 'Saints'), ('Eminent Persons', 'Eminent Persons')], default='Laity', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='churchandotherbuilding',
            name='category',
            field=models.CharField(choices=[('Basilica', 'Basilica'), ('Cathedrals', 'Cathedrals'), ('Parishes', 'Parishes'), ('Pilgrime Centers', 'Pilgrime Centers')], max_length=60),
        ),
        migrations.AlterField(
            model_name='institutionbuilding',
            name='category',
            field=models.CharField(choices=[('Universities', 'Universities'), ('Colleges', 'Colleges'), ('Schools', 'Schools'), ('Technical Institutions', 'Technical Institutions'), ('Medical Colleges', 'Medical Colleges'), ('Hospitals', 'Hospitals'), ('Charity Institutions', 'Charity Institutions'), ('Amenity Centres', 'Amenity Centres')], max_length=50),
        ),
    ]
