# Generated by Django 5.0.7 on 2024-10-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0009_churchcommunity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchcommunity',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='about_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='about_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='beliefs_and_teachings_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='beliefs_and_teachings_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='beliefs_and_teachings_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='community_life_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='community_life_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='community_life_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='conclusion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='conclusion_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='conclusion_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='historical_figures_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='historical_figures_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='historical_figures_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='name_hi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='name_ml',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='worship_practices_and_rituals_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='worship_practices_and_rituals_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='worship_practices_and_rituals_ml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
