# Generated by Django 5.0.7 on 2024-10-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0010_churchcommunity_about_en_churchcommunity_about_hi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchcommunity',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='name_ml',
        ),
    ]
