# Generated by Django 5.0.7 on 2024-10-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0011_remove_churchcommunity_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchcommunity',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='about_hi',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='about_ml',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='beliefs_and_teachings_en',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='beliefs_and_teachings_hi',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='beliefs_and_teachings_ml',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='community_life_en',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='community_life_hi',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='community_life_ml',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='conclusion_en',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='conclusion_hi',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='conclusion_ml',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='historical_figures_en',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='historical_figures_hi',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='historical_figures_ml',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='worship_practices_and_rituals_en',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='worship_practices_and_rituals_hi',
        ),
        migrations.RemoveField(
            model_name='churchcommunity',
            name='worship_practices_and_rituals_ml',
        ),
    ]
