# Generated by Django 5.0.7 on 2024-10-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0012_remove_churchcommunity_about_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='about_ml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
