# Generated by Django 5.0.7 on 2024-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0013_majorcelebrationhistoricalevent_about_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchcommunity',
            name='about_ml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
