# Generated by Django 5.0.7 on 2024-10-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0014_churchcommunity_about_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchcommunity',
            name='about_hi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
