# Generated by Django 5.0.7 on 2024-10-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0015_churchcommunity_about_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchcommunity',
            name='beliefs_and_teachings_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='beliefs_and_teachings_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='community_life_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='community_life_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='conclusion_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='conclusion_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='governance_and_structure_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='governance_and_structure_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='historical_figures_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='historical_figures_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='worship_practices_and_rituals_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchcommunity',
            name='worship_practices_and_rituals_ml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
