# Generated by Django 5.0.7 on 2024-11-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0016_churchcommunity_beliefs_and_teachings_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='about_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='about_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='architecture_and_design_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='architecture_and_design_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='community_impact_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='community_impact_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='conclusion_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='conclusion_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='functions_and_services_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='functions_and_services_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='governance_and_leadership_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='governance_and_leadership_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='history_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='history_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='notable_features_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchandotherbuilding',
            name='notable_features_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='about_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='about_ml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
