# Generated by Django 5.0.7 on 2024-11-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceapp', '0017_churchandotherbuilding_about_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionbuilding',
            name='about_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='about_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='conclusion_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='conclusion_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='governance_and_leadership_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='governance_and_leadership_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='history_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='history_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='impact_and_reach_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='impact_and_reach_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='mission_and_values_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='mission_and_values_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='notable_achievements_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='notable_achievements_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='services_and_programs_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionbuilding',
            name='services_and_programs_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='about_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='background_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='background_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='commemoration_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='commemoration_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='conclusion_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='conclusion_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='impact_and_significance_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='impact_and_significance_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='the_event_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='majorcelebrationhistoricalevent',
            name='the_event_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='conclusion_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='conclusion_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='early_life_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='early_life_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='influence_and_legacy_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='influence_and_legacy_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='key_achievements_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='key_achievements_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='personal_reflections_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='personal_reflections_ml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='veneration_recognition_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='veneration_recognition_ml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
